[package]
name = "libbitcoin-rs"
version = "0.1.0"
authors = ["Janus <janus@dark.fi>"]
edition = "2018"

[dependencies]
cxx = "1.0.49"
autocxx = "0.8.0"

[build-dependencies]
pkg-config = "0.3.19"
#autocxx-build = { git ="https://github.com/google/autocxx",package="autocxx-build", branch = "main" }
autocxx-build = "0.8.0"
